name: Spotify STS Build

env:
  AZURE_WEBAPP_NAME: spotifylike-sectokenservice
  DOTNET_VERSION: '8'       

on:
  push:
    branches: [ "main" ]
    paths:
      - SpotifyLike.STS/**

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Set up dependency caching for faster builds
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Build with dotnet
        run: dotnet build ./SpotifyLike.STS --configuration Release
      
      - name: Docker Login
        uses: azure/docker-login@v1
        with:
          login-server: ${{secrets.REGISTRY_LOGIN_SERVER}}
          username: ${{secrets.REGISTRY_USERNAME}}
          password: ${{secrets.REGISTRY_PASSWORD}}
      - name: Build image and push
        uses: docker/build-push-action@v5
        with:
          push: true
          file: SpotifyLike.STS/Dockerfile
          context: .
          tags: ${{secrets.REGISTRY_LOGIN_SERVER}}/spotify-sts:${{github.sha}}

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Lowercase the repo name and username
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_STS }}
          images: '${{secrets.REGISTRY_LOGIN_SERVER}}/spotify-sts:${{ github.sha }}'


      

      
